default-config: &default-config
  docker:
    - image: circleci/node:8.11-browsers
  working_directory: ~/repo
version: 2
jobs:
  build:
    <<: *default-config
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - deps-{{ checksum "package.json" }}-
            - deps-
      - run:
          name: Install dependencies
          command: |
            cd src
            npm install --no-save
      - save_cache:
          key: deps-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run the Linter
          command: npm run lint
      - run:
          name: Run the Unit Tests
          command: npm run test
      - run:
          name: Build
          command: npm run deploy
